### PR TITLE
Add edition metadata for Product Recommendations SDK

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Description

Add [edition keyword](https://github.com/adobe/aio-theme#edition-keyword) metadata to Product Recommendations SDK.

## Related Issue

#27 

## Motivation and Context

While reviewing https://github.com/magento-commerce/devdocs/pull/3206, I noticed that the Product Recommendations topic has the [`ee_only: true`](https://github.com/magento-commerce/devdocs/pull/3206/files#diff-664c977119786d362cbffcda991da82889c5bddc5c0bb4787502b9a0f7e37f27R4) property set. This PR adds the equivalent property for devsite repos.

## How Has This Been Tested?

GitHub Actions PR validation

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jhadobe** [comment]
Thanks for catching this, @jeff-matthews!

**Review by jhadobe — CHANGES_REQUESTED** [review]
@jeff-matthews should add the ee metadata to the `catalog-saas-export-module.md` file as well? it is essentially a subpage of the main SDK page.

**Comment by jeff-matthews** [comment]
@jhadobe, maybe? Where is the info currently published? I don't see any notes about it being commerce only. Just that it's a requirement to use the SDK.

**Comment by jhadobe** [comment]
@jeff-matthews it was previously published on @erikmarr's [personal github page](https://gist.github.com/erikmarr/36a9f293dc78fefa2ec567c4b48bddee), i moved it after [this comment](https://github.com/AdobeDocs/commerce-services/pull/27#discussion_r999908550)

**Comment by jeff-matthews** [comment]
I see it now. It's a [gist](https://gist.github.com/erikmarr/36a9f293dc78fefa2ec567c4b48bddee) that belongs to @erikmarr. 

@erikmarr, is the Catalog SaaS Export Module for Adobe Commerce only?

**Comment by erikmarr** [comment]
@jhadobe the Catalog SaaS Export Module is not just for Adobe Commerce. It's for Open Source as well. Some services that use that module, such as PREX and Live Search are Commerce only, which I think is where the confusion originated.

**Review by jhadobe — APPROVED** [review]

**Pull request merged**
