### PR TITLE
Add a linter to validate external links

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR):
- Adds a plugin [remark-lint-no-dead-urls](https://github.com/remarkjs/remark-lint-no-dead-urls) to ensure that external URLs in Markdown pages are working. The linter returns warnings on https://www.php.net/ on working links in some reason (I assume server related issues) so I excluded this domain in the configuration.
- Replaces or removes dead links

Internal ticket: COMDOX-156

## Test

[Failed validate job](https://github.com/AdobeDocs/commerce-testing/actions/runs/6948160793/job/18903522012#step:11:12) reporting about dead links.

### CODE REVIEW

**Comment by dshevtsov** [comment]
- [ ] @keharper please see a [report](https://github.com/AdobeDocs/commerce-services/actions/runs/6949892530/job/18908934343?pr=75#step:11:14) about a dead link. Which link should I use instead?
- [ ] @jhadobe please see a [report](https://github.com/AdobeDocs/commerce-services/actions/runs/6949892530/job/18908934343?pr=75#step:11:17) about a dead link. Which link should I use instead?

**Comment by jhadobe** [comment]
> Request for help to the contributors whose changes were the last in affected lines:
> 
> * [ ]  @jhadobe please see a [report](https://github.com/AdobeDocs/commerce-services/actions/runs/6950486000/job/18910724545?pr=75#step:11:14) about a dead link. Which link should I use instead?

@keharper what link should replace https://github.com/magento/data-services-eap/tree/master/DataServices/docs/README.md#how-to-enroll ?

**Comment by keharper** [comment]
Pinging @erikmarr

**Comment by erikmarr** [comment]
@keharper I believe that should go here:
https://github.com/magento-commerce/data-services/blob/af8404441889db83b27d06af1324b64b02305cd1/DataServices/docs/README.md#how-to-enroll

**Comment by keharper** [comment]
@erikmarr That's a very specific/weird branch to link to. Can the branch be changed to main?

https://github.com/magento-commerce/data-services/blob/main/DataServices/docs/README.md

**Comment by erikmarr** [comment]
@keharper yes that can be changed to main. The URL I posted was the result of a search. Thanks for catching that.

**Comment by jhadobe** [comment]
@dshevtsov @keharper @erikmarr I would propose that we remove the link entirely. After looking at the content, it seems to be referencing early enrollment to product recommendations etc, for 2019. I assume we do not need to direct anyone to outdated enroll data.

**Comment by erikmarr** [comment]
@jhadobe I think you're right. I vaguely recall setting that up for our beta users. I agree the link should be removed.

**Review by jhadobe — APPROVED** [review]

**Pull request merged**
