### PR TITLE
COMDOX-1116: Enable OpenAPI linting

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR) updates linting in the project:
- adds OpenAPI linting
- deletes local linting as unsupported for ARM architecture
- upgrades SuperLinter version
- fixes new linter violations

## Affected pages

- none

### CODE REVIEW

**Comment by dshevtsov** [comment]
@mslabko we are implementing OpenAPI linter for this repository. Please verify if the following reported errors are relevant:

```
/github/workspace/src/openapi/data-ingestion-schema-v1.yaml
   446:39  error  oas3-valid-media-example  "SimpleProductWithImages.value" property must exist  paths./v1/catalog/products/{DATA_SPACE_ID}.patch.requestBody.content.application/json.examples.SimpleProductWithImages
   848:25  error  oas3-valid-media-example  "0" property must match exactly one schema in oneOf  paths./v1/catalog/products/prices/{DATA_SPACE_ID}.post.requestBody.content.application/json.examples.FeedWithNewProductPrice.value[1].discounts[0]
   848:34  error  oas3-valid-media-example  "code" property type must be object                  paths./v1/catalog/products/prices/{DATA_SPACE_ID}.post.requestBody.content.application/json.examples.FeedWithNewProductPrice.value[1].discounts[0].code
   937:25  error  oas3-valid-media-example  "0" property must match exactly one schema in oneOf  paths./v1/catalog/products/prices/{DATA_SPACE_ID}.patch.requestBody.content.application/json.examples.FeedWithProductPricesInformation.value[0].discounts[0]
   937:34  error  oas3-valid-media-example  "code" property type must be object                  paths./v1/catalog/products/prices/{DATA_SPACE_ID}.patch.requestBody.content.application/json.examples.FeedWithProductPricesInformation.value[0].discounts[0].code
```

**Comment by dshevtsov** [comment]
See [oas3-valid-media-example](https://meta.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules#oas3-valid-media-example) for details about the linter's rule.

**Review by jeff-matthews — COMMENTED** [review]
If docs still render even with errors, it makes me think we need to either 1) fix errors, 2) change `error` to `warn` to not fail builds, or 2) allow bypassing the check to prevent blocking early access customer builds on staging.

**Comment by dshevtsov** [comment]
If we do not fix the errors, there is not much value of enabling the linter.

**Comment by jeff-matthews** [comment]
I think the value is in seeing if there are errors to fix. Without the linter, we won't know unless the docs don't render properly.

**Comment by dshevtsov** [comment]
> @mslabko we are implementing OpenAPI linter for this repository. Please verify if the following reported errors are relevant:
> 
> ```
> src/openapi/data-ingestion-schema-v1.yaml
>    446:39  error  oas3-valid-media-example  "SimpleProductWithImages.value" property must exist  paths./v1/catalog/products/{DATA_SPACE_ID}.patch.requestBody.content.application/json.examples.SimpleProductWithImages
>    848:25  error  oas3-valid-media-example  "0" property must match exactly one schema in oneOf  paths./v1/catalog/products/prices/{DATA_SPACE_ID}.post.requestBody.content.application/json.examples.FeedWithNewProductPrice.value[1].discounts[0]
>    848:34  error  oas3-valid-media-example  "code" property type must be object                  paths./v1/catalog/products/prices/{DATA_SPACE_ID}.post.requestBody.content.application/json.examples.FeedWithNewProductPrice.value[1].discounts[0].code
>    937:25  error  oas3-valid-media-example  "0" property must match exactly one schema in oneOf  paths./v1/catalog/products/prices/{DATA_SPACE_ID}.patch.requestBody.content.application/json.examples.FeedWithProductPricesInformation.value[0].discounts[0]
>    937:34  error  oas3-valid-media-example  "code" property type must be object                  paths./v1/catalog/products/prices/{DATA_SPACE_ID}.patch.requestBody.content.application/json.examples.FeedWithProductPricesInformation.value[0].discounts[0].code
> ```

The reported errors relate to the examples, they are not valid against their defined schema.

**Comment by dshevtsov** [comment]
I'll take a look. Maybe I'll be able to fix them.

**Review by mslabko — APPROVED** [review]

**Pull request merged**
